version: "3.7"

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../src:/var/www/

  nginx:
    build:
      context: ./nginx
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d

  mariadb:
    build:
      context: ./mariadb
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=gideon
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./database/data:/var/lib/mysql



